name: Cwall
favicon: null
layout_spectrum: 0.89256920828484
typography_spectrum: 0.04165833885781467
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.31215844699181616
  lightness: 0.05879682628437877
  saturation: 0.10770640941336751
  rhythmicContrast: 0.7846719385124743
purpose: []
